### ISSUE TITLE
Add error handling for pipeline if there are not changes to commit

### ISSUE THREAD

**Issue by KarenJewell** [OpenDataScotland/opendata.scot_pipeline#9] opened 2023-05-26 19:05 UTC
**Describe the bug**
In the Dataset Pull Automation pipeline (the weekly friday refresh) in gh actions - if there are no changes to commit, the pipeline errors.

**To Reproduce**
1. Run the pipeline once successfully so all new changes are committed.
2. Run the pipeline again immediately after and this will result in no new changes to commit.

**Expected behavior**
Instead of erroring and no slack message being sent, handle this specific error and post to slack "no changes made to dataset listing after refresh" << feel free to modify slack message wording.

**Screenshots**
![Screenshot 2023-05-26 at 20 00 43](https://github.com/OpenDataScotland/opendata.scot_pipeline/assets/47697803/39e60647-9268-4896-97c3-dd0dccb541ad)

**Hardware and software used**
N/A

**Additional context**

**Comment by JackGilmore** [comment] 2023-09-02 11:25
Closing as duplicate of #5

**Closed as not planned** 2023-09-02 11:25 UTC
Labels: bug
